# Data cleaning and descriptive stats

Overview of today's learning goals:

  1. Introduce pandas
  2. Load data files
  3. Clean and process data
  4. Select, filter, and slice data from a dataset
  5. Descriptive stats: central tendency and dispersion
  6. Merging and concatenating datasets
  7. Grouping and summarizing data

In [1]:
!curl -s -o pyproject.toml https://raw.githubusercontent.com/gboeing/ppd534/refs/heads/main/pyproject.toml && uv pip install -q -r pyproject.toml

In [2]:
# something new: import these packages to work with data
import numpy as np
import pandas as pd
from google.colab import drive

# mount your google drive
drive.mount("/content/drive")

Mounted at /content/drive

## 1. Introducing pandas

https://pandas.pydata.org/

In [3]:
# review: a python list is a built-in data type
my_list = [8, 6, 4, 2]
my_list

[8, 6, 4, 2]

In [4]:
# a numpy array is like a list
# but faster, more compact, and lots more features
my_array = np.array(my_list)
my_array

array([8, 6, 4, 2])

pandas has two primary data structures we will work with: Series and DataFrames

### 1a. pandas Series

In [5]:
# a pandas series is based on a numpy array: it's fast, compact, and has more functionality
# perhaps most notably, it has an index which allows you to work naturally with tabular data
my_series = pd.Series(my_list)
my_series

0    8
1    6
2    4
3    2
dtype: int64

In [6]:
# look at a list-representation of the index
my_series.index.tolist()

[0, 1, 2, 3]

In [7]:
# look at the series' values themselves
my_series.values

array([8, 6, 4, 2])

In [8]:
# what's the data type of the series' values?
type(my_series.values)

numpy.ndarray

In [9]:
# what's the data type of the individual values themselves?
my_series.dtype

dtype('int64')

### 1b. pandas DataFrames

In [10]:
# a dict can contain multiple lists and label them
my_dict = {
    "hh_income": [75125, 22075, 31950, 115400],
    "home_value": [525000, 275000, 395000, 985000],
}
my_dict

{'hh_income': [75125, 22075, 31950, 115400],
 'home_value': [525000, 275000, 395000, 985000]}

In [11]:
# a pandas dataframe can contain one or more columns
# each column is a pandas series
# each row is a pandas series
# you can create a dataframe by passing in a list, array, series, or dict
df = pd.DataFrame(my_dict)
df

   hh_income  home_value
0      75125      525000
1      22075      275000
2      31950      395000
3     115400      985000

In [12]:
# the row labels in the index are accessed by the .index attribute of the DataFrame object
df.index.tolist()

[0, 1, 2, 3]

In [13]:
# the column labels are accessed by the .columns attribute of the DataFrame object
df.columns

Index(['hh_income', 'home_value'], dtype='object')

In [14]:
# the data values are accessed by the .values attribute of the DataFrame object
# this is a numpy (two-dimensional) array
df.values

array([[ 75125, 525000],
       [ 22075, 275000],
       [ 31950, 395000],
       [115400, 985000]])

## 2. Loading data

In practice, you'll work with data by loading a dataset file into pandas. CSV is the most common format. But pandas can also ingest tab-separated data, JSON, and proprietary file formats like Excel .xlsx files, Stata, SAS, and SPSS.

Below, notice what pandas's `read_csv` function does:

1. recognize the header row and get its variable names
1. read all the rows and construct a pandas DataFrame (an assembly of pandas Series rows and columns)
1. construct a unique index, beginning with zero
1. infer the data type of each variable (ie, column)

In [18]:
# load a data file
# note the dtype argument! always specify that fips codes are strings, otherwise pandas guesses int
filepath = "https://raw.githubusercontent.com/gboeing/ppd534/main/data/census_tracts_data_la.csv"
df = pd.read_csv(filepath, dtype={"GEOID10": str})

In [17]:
# dataframe shape as rows, columns
df.shape

(2346, 25)

In [19]:
# or use len to just see the number of rows
len(df)

2346

In [20]:
# view the dataframe's "head"
df.head()

,GEOID10,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,...,med_gross_rent,med_household_income,mean_commute_time,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born
0,06037106010,3342.0,38.2,73.6,14.8,3.6,145.0,47.0,77.2,460800.0,...,1471 (USD),$73650,31.5,76.2,21.3,23.8,87.9,20.4,42.1,28.1
1,06037106020,5937.0,37.9,81.1,15.4,1.0,92.0,51.9,95.8,441100.0,...,1924 (USD),$74286,32.6,82.5,11.4,36.9,95.1,15.5,29.0,37.5
2,06037134720,4645.0,33.6,46.9,23.2,5.0,991.0,49.9,40.2,450600.0,...,1418 (USD),$61372,28.0,73.6,13.0,32.6,87.4,25.0,32.6,42.2
3,06037137201,6226.0,33.4,19.2,53.6,4.9,1315.0,50.8,34.9,605300.0,...,1763 (USD),$74936,29.3,71.3,7.1,29.9,86.0,51.0,54.5,39.2
4,06037137502,4627.0,41.9,13.2,67.2,10.8,174.0,47.1,77.0,668400.0,...,2325 (USD),$96964,32.0,84.9,5.7,22.9,80.8,54.9,77.9,20.1

In [21]:
# view the dataframe's "tail"
df.tail()

,GEOID10,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,...,med_gross_rent,med_household_income,mean_commute_time,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born
2341,06037670326,3488.0,52.6,6.2,56.4,1.4,1040.0,51.7,98.2,1869400.0,...,3501 (USD),$155000,36.4,81.2,6.3,18.3,87.8,77.5,69.6,25.0
2342,06037670324,5167.0,48.4,9.9,71.4,0.4,740.0,44.7,89.4,1541100.0,...,2756 (USD),$207679,30.5,81.0,5.1,19.7,89.7,71.4,80.1,15.0
2343,06037651402,6259.0,41.8,12.1,35.8,0.0,2931.0,50.2,66.4,804200.0,...,1421 (USD),$113616,31.9,87.3,4.6,23.8,88.1,58.8,53.2,37.7
2344,06037800203,5586.0,42.1,8.8,78.8,0.0,507.0,49.6,67.9,1595800.0,...,2332 (USD),$123224,30.8,75.3,7.6,21.0,78.8,59.4,75.5,20.7
2345,06037700102,3915.0,41.3,13.1,70.2,8.7,157.0,54.6,9.6,562500.0,...,1297 (USD),$36356,27.7,74.5,19.7,68.1,93.1,48.7,53.0,34.5

#### What are these data?

I gathered them from the census bureau (2017 5-year tract-level ACS) for you, then gave them meaningful variable names. It's a set of socioeconomic variables across all LA County census tracts:

|column|description|
|------|-----------|
|total_pop|Estimate!!SEX AND AGE!!Total population|
|median_age|Estimate!!SEX AND AGE!!Total population!!Median age (years)|
|pct_hispanic|Percent Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)|
|pct_white|Percent Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone|
|pct_black|Percent Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone|
|pct_asian|Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone|
|pct_male|Percent Estimate!!SEX AND AGE!!Total population!!Male|
|pct_single_family_home|Percent Estimate!!UNITS IN STRUCTURE!!Total housing units!!1-unit detached|
|med_home_value|Estimate!!VALUE!!Owner-occupied units!!Median (dollars)|
|med_rooms_per_home|Estimate!!ROOMS!!Total housing units!!Median rooms|
|pct_built_before_1940|Percent Estimate!!YEAR STRUCTURE BUILT!!Total housing units!!Built 1939 or earlier|
|pct_renting|Percent Estimate!!HOUSING TENURE!!Occupied housing units!!Renter-occupied|
|rental_vacancy_rate|Estimate!!HOUSING OCCUPANCY!!Total housing units!!Rental vacancy rate|
|avg_renter_household_size|Estimate!!HOUSING TENURE!!Occupied housing units!!Average household size of renter-occupied unit|
|med_gross_rent|Estimate!!GROSS RENT!!Occupied units paying rent!!Median (dollars)|
|med_household_income|Estimate!!INCOME AND BENEFITS (IN 2017 INFLATION-ADJUSTED DOLLARS)!!Total households!!Median household income (dollars)|
|mean_commute_time|Estimate!!COMMUTING TO WORK!!Workers 16 years and over!!Mean travel time to work (minutes)|
|pct_commute_drive_alone|Percent Estimate!!COMMUTING TO WORK!!Workers 16 years and over!!Car truck or van drove alone|
|pct_below_poverty|Percent Estimate!!PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people|
|pct_college_grad_student|Percent Estimate!!SCHOOL ENROLLMENT!!Population 3 years and over enrolled in school!!College or graduate school|
|pct_same_residence_year_ago|Percent Estimate!!RESIDENCE 1 YEAR AGO!!Population 1 year and over!!Same house|
|pct_bachelors_degree|Percent Estimate!!EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Percent bachelor's degree or higher|
|pct_english_only|Percent Estimate!!LANGUAGE SPOKEN AT HOME!!Population 5 years and over!!English only|
|pct_foreign_born|Percent Estimate!!PLACE OF BIRTH!!Total population!!Foreign born|

## 3. Clean and process data

In [22]:
df.head(10)

,GEOID10,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,...,med_gross_rent,med_household_income,mean_commute_time,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born
0,06037106010,3342.0,38.2,73.6,14.8,3.6,145.0,47.0,77.2,460800.0,...,1471 (USD),$73650,31.5,76.2,21.3,23.8,87.9,20.4,42.1,28.1
1,06037106020,5937.0,37.9,81.1,15.4,1.0,92.0,51.9,95.8,441100.0,...,1924 (USD),$74286,32.6,82.5,11.4,36.9,95.1,15.5,29.0,37.5
2,06037134720,4645.0,33.6,46.9,23.2,5.0,991.0,49.9,40.2,450600.0,...,1418 (USD),$61372,28.0,73.6,13.0,32.6,87.4,25.0,32.6,42.2
3,06037137201,6226.0,33.4,19.2,53.6,4.9,1315.0,50.8,34.9,605300.0,...,1763 (USD),$74936,29.3,71.3,7.1,29.9,86.0,51.0,54.5,39.2
4,06037137502,4627.0,41.9,13.2,67.2,10.8,174.0,47.1,77.0,668400.0,...,2325 (USD),$96964,32.0,84.9,5.7,22.9,80.8,54.9,77.9,20.1
5,06037137504,1960.0,52.0,3.3,91.6,1.4,39.0,51.4,96.9,1101700.0,...,NaN,$175313,32.1,72.9,2.3,21.1,87.4,58.8,72.3,24.7
6,06037139702,5985.0,50.1,3.0,86.3,3.3,340.0,48.6,100.0,1247600.0,...,2934 (USD),$187891,31.9,83.4,4.7,9.1,94.1,69.0,58.3,34.2
7,06037143500,4977.0,41.4,9.4,69.7,11.8,281.0,46.9,37.5,908000.0,...,1795 (USD),$87464,32.2,69.5,10.3,11.1,86.2,64.2,82.6,11.9
8,06037181400,4511.0,40.6,37.9,24.9,1.3,1518.0,47.5,38.7,643300.0,...,1401 (USD),$55208,27.7,75.9,12.1,34.1,89.3,40.6,48.3,40.6
9,06037189400,3497.0,42.4,6.7,79.0,3.6,210.0,49.6,66.7,1131200.0,...,1825 (USD),$123500,31.2,70.1,8.3,27.2,89.0,70.4,86.1,13.2

In [23]:
# data types of the columns
df.dtypes

GEOID10                         object
total_pop                      float64
median_age                     float64
pct_hispanic                   float64
pct_white                      float64
pct_black                      float64
pct_asian                      float64
pct_male                       float64
pct_single_family_home         float64
med_home_value                 float64
med_rooms_per_home             float64
pct_built_before_1940          float64
pct_renting                    float64
rental_vacancy_rate            float64
avg_renter_household_size      float64
med_gross_rent                  object
med_household_income            object
mean_commute_time              float64
pct_commute_drive_alone        float64
pct_below_poverty              float64
pct_college_grad_student       float64
pct_same_residence_year_ago    float64
pct_bachelors_degree           float64
pct_english_only               float64
pct_foreign_born               float64
dtype: object

In [24]:
# access a single column like df['col_name']
df["med_gross_rent"].head(10)

0    1471 (USD)
1    1924 (USD)
2    1418 (USD)
3    1763 (USD)
4    2325 (USD)
5           NaN
6    2934 (USD)
7    1795 (USD)
8    1401 (USD)
9    1825 (USD)
Name: med_gross_rent, dtype: object

In [25]:
# pandas uses numpy's nan to represent null (missing) values
print(np.nan)
print(type(np.nan))

nan
<class 'float'>

In [27]:
# convert rent from string -> float
df["med_gross_rent"].astype(float)

ValueError: could not convert string to float: '1471 (USD)'

Didn't work! We need to clean up the stray alphabetical characters to get a numerical value. You can do string operations on pandas Series to clean up their values

In [30]:
# do a string replace and assign back to that column, then change type to float
df["med_gross_rent"] = df["med_gross_rent"].str.replace(" (USD)", "", regex=False)
df["med_gross_rent"] = df["med_gross_rent"].astype(float)

AttributeError: Can only use .str accessor with string values!

In [32]:
# now clean up the income column then convert it from string -> float
# do a string replace and assign back to that column
df["med_household_income"] = df["med_household_income"].str.replace("$", "", regex=False)
df["med_household_income"] = df["med_household_income"].astype(float)

AttributeError: Can only use .str accessor with string values!

In [33]:
# convert rent from float -> int
df["med_gross_rent"].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

You cannot store null values as type `int`, only as type `float`. You have three basic options:

  1. Keep the column as float to retain the nulls - they are often important!
  2. Drop all the rows that contain nulls if we need non-null data for our analysis
  3. Fill in all the nulls with another value if we know a reliable default value

In [34]:
df.shape

(2346, 25)

In [35]:
# drop rows that contain nulls
# this doesn't save result, because we didn't reassign! (in reality, want to keep the nulls here)
df.dropna(subset=["med_gross_rent"]).shape

(2298, 25)

In [36]:
# fill in rows that contain nulls
# this doesn't save result, because we didn't reassign! (in reality, want to keep the nulls here)
df["med_gross_rent"].fillna(value=0).head(10)

0    1471.0
1    1924.0
2    1418.0
3    1763.0
4    2325.0
5       0.0
6    2934.0
7    1795.0
8    1401.0
9    1825.0
Name: med_gross_rent, dtype: float64

In [37]:
# more string operations: slice state fips and county fips out of the tract fips string
# assign them to new dataframe columns
df["state"] = df["GEOID10"].str.slice(0, 2)
df["county"] = df["GEOID10"].str.slice(2, 5)
df.head()

,GEOID10,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,...,mean_commute_time,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born,state,county
0,06037106010,3342.0,38.2,73.6,14.8,3.6,145.0,47.0,77.2,460800.0,...,31.5,76.2,21.3,23.8,87.9,20.4,42.1,28.1,06,037
1,06037106020,5937.0,37.9,81.1,15.4,1.0,92.0,51.9,95.8,441100.0,...,32.6,82.5,11.4,36.9,95.1,15.5,29.0,37.5,06,037
2,06037134720,4645.0,33.6,46.9,23.2,5.0,991.0,49.9,40.2,450600.0,...,28.0,73.6,13.0,32.6,87.4,25.0,32.6,42.2,06,037
3,06037137201,6226.0,33.4,19.2,53.6,4.9,1315.0,50.8,34.9,605300.0,...,29.3,71.3,7.1,29.9,86.0,51.0,54.5,39.2,06,037
4,06037137502,4627.0,41.9,13.2,67.2,10.8,174.0,47.1,77.0,668400.0,...,32.0,84.9,5.7,22.9,80.8,54.9,77.9,20.1,06,037

In [39]:
# dict that maps state fips code -> state name
fips = {"04": "Arizona", "06": "California", "41": "Oregon"}

# replace fips code with state name with the replace() method
df["state"] = df["state"].replace(fips)

In [41]:
# you can rename columns with the rename() method
# remember to reassign to save the result
df = df.rename(columns={"state": "state_name"})

In [42]:
# you can drop columns you don't need with the drop() method
# remember to reassign to save the result
df = df.drop(columns=["county"])

In [43]:
# inspect the cleaned-up dataframe
df.head()

,GEOID10,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,...,med_household_income,mean_commute_time,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born,state_name
0,06037106010,3342.0,38.2,73.6,14.8,3.6,145.0,47.0,77.2,460800.0,...,73650.0,31.5,76.2,21.3,23.8,87.9,20.4,42.1,28.1,California
1,06037106020,5937.0,37.9,81.1,15.4,1.0,92.0,51.9,95.8,441100.0,...,74286.0,32.6,82.5,11.4,36.9,95.1,15.5,29.0,37.5,California
2,06037134720,4645.0,33.6,46.9,23.2,5.0,991.0,49.9,40.2,450600.0,...,61372.0,28.0,73.6,13.0,32.6,87.4,25.0,32.6,42.2,California
3,06037137201,6226.0,33.4,19.2,53.6,4.9,1315.0,50.8,34.9,605300.0,...,74936.0,29.3,71.3,7.1,29.9,86.0,51.0,54.5,39.2,California
4,06037137502,4627.0,41.9,13.2,67.2,10.8,174.0,47.1,77.0,668400.0,...,96964.0,32.0,84.9,5.7,22.9,80.8,54.9,77.9,20.1,California

In [44]:
# save it to disk as a "clean" copy
# note the filepath
filepath = "/content/drive/My Drive/Colab Notebooks/census_tracts_data_la-clean.csv"
df.to_csv(filepath, index=False, encoding="utf-8")

OSError: Cannot save file into a non-existent directory: '/content/drive/My Drive/Colab Notebooks'

In [45]:
# and you can read it back in
pd.read_csv(filepath)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/Colab Notebooks/census_tracts_data_la-clean.csv'

## 4. Selecting and slicing data from a DataFrame

In [46]:
# CHEAT SHEET OF COMMON TASKS
# Operation                       Syntax           Result
# ------------------------------------------------------------
# Select column by name           df[col]          Series
# Select columns by name          df[col_list]     DataFrame
# Select row by label             df.loc[label]    Series
# Select row by integer location  df.iloc[loc]     Series
# Slice rows by label             df.loc[a:c]      DataFrame
# Select rows by boolean vector   df[mask]         DataFrame

### 4a. Select DataFrame's column(s) by name

We saw some of this a minute ago. Let's look in a bit more detail and break down what's happening.

In [47]:
# select a single column by column name
# this is a pandas series
df["total_pop"]

0       3342.0
1       5937.0
2       4645.0
3       6226.0
4       4627.0
         ...
2341    3488.0
2342    5167.0
2343    6259.0
2344    5586.0
2345    3915.0
Name: total_pop, Length: 2346, dtype: float64

In [48]:
# select multiple columns by a list of column names
# this is a pandas dataframe that is a subset of the original
df[["total_pop", "median_age"]]

      total_pop  median_age
0        3342.0        38.2
1        5937.0        37.9
2        4645.0        33.6
3        6226.0        33.4
4        4627.0        41.9
...         ...         ...
2341     3488.0        52.6
2342     5167.0        48.4
2343     6259.0        41.8
2344     5586.0        42.1
2345     3915.0        41.3

[2346 rows x 2 columns]

In [49]:
# create a new column by assigning df['new_col'] to some set of values
# you can do math operations on any numeric columns
df["monthly_income"] = df["med_household_income"] / 12
df["rent_burden"] = df["med_gross_rent"] / df["monthly_income"]

# inspect the results
df[["med_household_income", "monthly_income", "med_gross_rent", "rent_burden"]].head()

   med_household_income  monthly_income  med_gross_rent  rent_burden
0               73650.0     6137.500000          1471.0     0.239674
1               74286.0     6190.500000          1924.0     0.310799
2               61372.0     5114.333333          1418.0     0.277260
3               74936.0     6244.666667          1763.0     0.282321
4               96964.0     8080.333333          2325.0     0.287736

### 4b. Select row(s) by label

In [50]:
# use .loc to select by row label
# returns the row as a series whose index is the dataframe column names
df.loc[0]

GEOID10                        06037106010
total_pop                           3342.0
median_age                            38.2
pct_hispanic                          73.6
pct_white                             14.8
pct_black                              3.6
pct_asian                            145.0
pct_male                              47.0
pct_single_family_home                77.2
med_home_value                    460800.0
med_rooms_per_home                     6.3
pct_built_before_1940                  2.1
pct_renting                           25.1
rental_vacancy_rate                    0.0
avg_renter_household_size             3.12
med_gross_rent                      1471.0
med_household_income               73650.0
mean_commute_time                     31.5
pct_commute_drive_alone               76.2
pct_below_poverty                     21.3
pct_college_grad_student              23.8
pct_same_residence_year_ago           87.9
pct_bachelors_degree                  20.4
pct_english_only                      42.1
pct_foreign_born                      28.1
state_name                      California
monthly_income                      6137.5
rent_burden                       0.239674
Name: 0, dtype: object

In [52]:
# use .loc to select single value by row label, column name
df.loc[0, "pct_below_poverty"]

np.float64(21.3)

In [53]:
# slice of rows from label 5 to label 7, inclusive
# this returns a pandas dataframe
df.loc[5:7]

,GEOID10,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,...,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born,state_name,monthly_income,rent_burden
5,06037137504,1960.0,52.0,3.3,91.6,1.4,39.0,51.4,96.9,1101700.0,...,72.9,2.3,21.1,87.4,58.8,72.3,24.7,California,14609.416667,NaN
6,06037139702,5985.0,50.1,3.0,86.3,3.3,340.0,48.6,100.0,1247600.0,...,83.4,4.7,9.1,94.1,69.0,58.3,34.2,California,15657.583333,0.187385
7,06037143500,4977.0,41.4,9.4,69.7,11.8,281.0,46.9,37.5,908000.0,...,69.5,10.3,11.1,86.2,64.2,82.6,11.9,California,7288.666667,0.246273

In [54]:
# slice of rows from label 1 to label 3, inclusive
# slice of columns from pct_hispanic to pct_asian, inclusive
df.loc[1:3, "pct_hispanic":"pct_asian"]

   pct_hispanic  pct_white  pct_black  pct_asian
1          81.1       15.4        1.0       92.0
2          46.9       23.2        5.0      991.0
3          19.2       53.6        4.9     1315.0

In [55]:
# subset of rows from with labels in list
# subset of columns with names in list
df.loc[[1, 3], ["pct_hispanic", "pct_asian"]]

   pct_hispanic  pct_asian
1          81.1       92.0
3          19.2     1315.0

In [58]:
# you can use a column of unique identifiers as the index
# fips codes uniquely identify each row (but verify!)
df = df.set_index("GEOID10")
df.index.is_unique

KeyError: "None of ['GEOID10'] are in the columns"

In [57]:
df.head()

,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,med_rooms_per_home,...,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born,state_name,monthly_income,rent_burden
GEOID10,,,,,,,,,,,,,,,,,,,,,
06037106010,3342.0,38.2,73.6,14.8,3.6,145.0,47.0,77.2,460800.0,6.3,...,76.2,21.3,23.8,87.9,20.4,42.1,28.1,California,6137.500000,0.239674
06037106020,5937.0,37.9,81.1,15.4,1.0,92.0,51.9,95.8,441100.0,6.2,...,82.5,11.4,36.9,95.1,15.5,29.0,37.5,California,6190.500000,0.310799
06037134720,4645.0,33.6,46.9,23.2,5.0,991.0,49.9,40.2,450600.0,4.2,...,73.6,13.0,32.6,87.4,25.0,32.6,42.2,California,5114.333333,0.277260
06037137201,6226.0,33.4,19.2,53.6,4.9,1315.0,50.8,34.9,605300.0,4.4,...,71.3,7.1,29.9,86.0,51.0,54.5,39.2,California,6244.666667,0.282321
06037137502,4627.0,41.9,13.2,67.2,10.8,174.0,47.1,77.0,668400.0,5.4,...,84.9,5.7,22.9,80.8,54.9,77.9,20.1,California,8080.333333,0.287736

In [59]:
# .loc works by label, not by position in the dataframe
df.loc[0]

KeyError: 0

In [60]:
# the index now contains fips codes, so you have to use .loc accordingly to select by row label
df.loc["06037137201"]

total_pop                           6226.0
median_age                            33.4
pct_hispanic                          19.2
pct_white                             53.6
pct_black                              4.9
pct_asian                           1315.0
pct_male                              50.8
pct_single_family_home                34.9
med_home_value                    605300.0
med_rooms_per_home                     4.4
pct_built_before_1940                  4.0
pct_renting                           61.5
rental_vacancy_rate                    0.0
avg_renter_household_size             2.87
med_gross_rent                      1763.0
med_household_income               74936.0
mean_commute_time                     29.3
pct_commute_drive_alone               71.3
pct_below_poverty                      7.1
pct_college_grad_student              29.9
pct_same_residence_year_ago           86.0
pct_bachelors_degree                  51.0
pct_english_only                      54.5
pct_foreign_born                      39.2
state_name                      California
monthly_income                 6244.666667
rent_burden                       0.282321
Name: 06037137201, dtype: object

### 4c. Select by (integer) position

In [61]:
# get the row in the zero-th position in the dataframe
df.iloc[0]

total_pop                          3342.0
median_age                           38.2
pct_hispanic                         73.6
pct_white                            14.8
pct_black                             3.6
pct_asian                           145.0
pct_male                             47.0
pct_single_family_home               77.2
med_home_value                   460800.0
med_rooms_per_home                    6.3
pct_built_before_1940                 2.1
pct_renting                          25.1
rental_vacancy_rate                   0.0
avg_renter_household_size            3.12
med_gross_rent                     1471.0
med_household_income              73650.0
mean_commute_time                    31.5
pct_commute_drive_alone              76.2
pct_below_poverty                    21.3
pct_college_grad_student             23.8
pct_same_residence_year_ago          87.9
pct_bachelors_degree                 20.4
pct_english_only                     42.1
pct_foreign_born                     28.1
state_name                     California
monthly_income                     6137.5
rent_burden                      0.239674
Name: 06037106010, dtype: object

In [62]:
# you can slice as well
# note, while .loc[] is inclusive, .iloc[] is not
# get the rows from position 0 up to but not including position 3 (ie, rows 0, 1, and 2)
df.iloc[0:3]

,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,med_rooms_per_home,...,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born,state_name,monthly_income,rent_burden
GEOID10,,,,,,,,,,,,,,,,,,,,,
06037106010,3342.0,38.2,73.6,14.8,3.6,145.0,47.0,77.2,460800.0,6.3,...,76.2,21.3,23.8,87.9,20.4,42.1,28.1,California,6137.500000,0.239674
06037106020,5937.0,37.9,81.1,15.4,1.0,92.0,51.9,95.8,441100.0,6.2,...,82.5,11.4,36.9,95.1,15.5,29.0,37.5,California,6190.500000,0.310799
06037134720,4645.0,33.6,46.9,23.2,5.0,991.0,49.9,40.2,450600.0,4.2,...,73.6,13.0,32.6,87.4,25.0,32.6,42.2,California,5114.333333,0.277260

In [63]:
# get the value from the row in position 3 and the column in position 2 (zero-indexed)
df.iloc[3, 2]

np.float64(19.2)

### 4d. Select/filter by value

You can subset or filter a dataframe for based on the values in its rows/columns.

In [64]:
# filter the dataframe by rows with 30%+ rent burden
df[df["rent_burden"] > 0.3]

,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,med_rooms_per_home,...,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born,state_name,monthly_income,rent_burden
GEOID10,,,,,,,,,,,,,,,,,,,,,
06037106020,5937.0,37.9,81.1,15.4,1.0,92.0,51.9,95.8,441100.0,6.2,...,82.5,11.4,36.9,95.1,15.5,29.0,37.5,California,6190.500000,0.310799
06037181400,4511.0,40.6,37.9,24.9,1.3,1518.0,47.5,38.7,643300.0,3.9,...,75.9,12.1,34.1,89.3,40.6,48.3,40.6,California,4600.666667,0.304521
06037189902,5243.0,35.6,8.6,72.6,2.9,641.0,55.5,1.1,535300.0,3.1,...,66.0,15.2,80.6,75.9,62.8,53.8,43.4,California,4343.333333,0.355257
06037190100,4624.0,32.6,17.4,62.0,6.5,463.0,57.5,5.0,608200.0,2.4,...,56.4,20.8,92.8,71.6,64.5,70.9,24.5,California,3539.166667,0.397551
06037199201,4170.0,30.7,66.5,1.1,0.0,1297.0,48.0,24.2,377500.0,3.6,...,59.4,24.9,21.7,92.4,11.2,14.1,46.9,California,3250.750000,0.312851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
06037910002,7884.0,30.8,65.7,23.9,5.3,37.0,48.5,96.6,209400.0,5.3,...,77.7,24.2,22.9,82.0,6.3,56.0,23.4,California,3352.500000,0.378225
06037900609,5574.0,27.4,46.5,20.8,26.6,174.0,48.5,58.8,127500.0,6.5,...,92.0,36.1,20.3,95.9,13.2,82.1,8.6,California,3635.916667,0.331966
06037650604,5825.0,35.4,14.5,32.6,2.4,2303.0,49.5,9.9,590300.0,3.3,...,77.2,11.5,27.9,73.6,43.7,44.7,45.8,California,4503.000000,0.326005
06037920336,6630.0,28.9,80.5,14.0,0.9,128.0,55.6,37.4,367700.0,4.0,...,61.5,26.1,16.1,82.6,12.0,26.3,45.3,California,4043.583333,0.326690
06037700102,3915.0,41.3,13.1,70.2,8.7,157.0,54.6,9.6,562500.0,3.2,...,74.5,19.7,68.1,93.1,48.7,53.0,34.5,California,3029.666667,0.428100

In [65]:
# what exactly did that do? let's break it out.
df["rent_burden"] > 0.3

GEOID10
06037106010    False
06037106020     True
06037134720    False
06037137201    False
06037137502    False
               ...
06037670326    False
06037670324    False
06037651402    False
06037800203    False
06037700102     True
Name: rent_burden, Length: 2346, dtype: bool

In [66]:
# essentially a true/false mask that filters by value
mask = df["rent_burden"] > 0.3
df[mask]

,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,med_rooms_per_home,...,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born,state_name,monthly_income,rent_burden
GEOID10,,,,,,,,,,,,,,,,,,,,,
06037106020,5937.0,37.9,81.1,15.4,1.0,92.0,51.9,95.8,441100.0,6.2,...,82.5,11.4,36.9,95.1,15.5,29.0,37.5,California,6190.500000,0.310799
06037181400,4511.0,40.6,37.9,24.9,1.3,1518.0,47.5,38.7,643300.0,3.9,...,75.9,12.1,34.1,89.3,40.6,48.3,40.6,California,4600.666667,0.304521
06037189902,5243.0,35.6,8.6,72.6,2.9,641.0,55.5,1.1,535300.0,3.1,...,66.0,15.2,80.6,75.9,62.8,53.8,43.4,California,4343.333333,0.355257
06037190100,4624.0,32.6,17.4,62.0,6.5,463.0,57.5,5.0,608200.0,2.4,...,56.4,20.8,92.8,71.6,64.5,70.9,24.5,California,3539.166667,0.397551
06037199201,4170.0,30.7,66.5,1.1,0.0,1297.0,48.0,24.2,377500.0,3.6,...,59.4,24.9,21.7,92.4,11.2,14.1,46.9,California,3250.750000,0.312851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
06037910002,7884.0,30.8,65.7,23.9,5.3,37.0,48.5,96.6,209400.0,5.3,...,77.7,24.2,22.9,82.0,6.3,56.0,23.4,California,3352.500000,0.378225
06037900609,5574.0,27.4,46.5,20.8,26.6,174.0,48.5,58.8,127500.0,6.5,...,92.0,36.1,20.3,95.9,13.2,82.1,8.6,California,3635.916667,0.331966
06037650604,5825.0,35.4,14.5,32.6,2.4,2303.0,49.5,9.9,590300.0,3.3,...,77.2,11.5,27.9,73.6,43.7,44.7,45.8,California,4503.000000,0.326005
06037920336,6630.0,28.9,80.5,14.0,0.9,128.0,55.6,37.4,367700.0,4.0,...,61.5,26.1,16.1,82.6,12.0,26.3,45.3,California,4043.583333,0.326690
06037700102,3915.0,41.3,13.1,70.2,8.7,157.0,54.6,9.6,562500.0,3.2,...,74.5,19.7,68.1,93.1,48.7,53.0,34.5,California,3029.666667,0.428100

In [67]:
# you can chain multiple conditions together
# pandas logical operators are: | for or, & for and, ~ for not
# these must be grouped by using parentheses due to order of operations
# question: which tracts are both rent-burdened and majority-Black?
mask = (df["rent_burden"] > 0.3) & (df["pct_black"] > 50)
df[mask].shape

(20, 27)

In [68]:
# which tracts are both rent-burdened and either majority-Black or majority-Hispanic?
mask1 = df["rent_burden"] > 0.3
mask2 = df["pct_black"] > 50
mask3 = df["pct_hispanic"] > 50
mask = mask1 & (mask2 | mask3)
df[mask].shape

(654, 27)

In [69]:
# see the mask
mask

GEOID10
06037106010    False
06037106020     True
06037134720    False
06037137201    False
06037137502    False
               ...
06037670326    False
06037670324    False
06037651402    False
06037800203    False
06037700102    False
Length: 2346, dtype: bool

In [70]:
# ~ means not... it essentially flips trues to falses and vice-versa
~mask

GEOID10
06037106010     True
06037106020    False
06037134720     True
06037137201     True
06037137502     True
               ...
06037670326     True
06037670324     True
06037651402     True
06037800203     True
06037700102     True
Length: 2346, dtype: bool

In [71]:
# which rows are in a state that begins with "Cal"?
# all of them... because we're looking only at LA county
mask = df["state_name"].str.startswith("Cal")
df[mask].shape

(2346, 27)

In [76]:
# now it's your turn
# create a new subset dataframe containing all the rows with median home values
# above $800,000 and percent-White above 60%... how many rows did you get?

(df["med_home_value"] > 800000) & (df["pct_white"] > 60)
df[mask].shape

(2346, 27)

## 5. Descriptive stats

In [77]:
# what share of majority-White tracts are rent burdened?
mask1 = df["pct_white"] > 50
mask2 = mask1 & (df["rent_burden"] > 0.3)
len(df[mask2]) / len(df[mask1])

0.23105360443622922

In [78]:
# what share of majority-Hispanic tracts are rent burdened?
mask1 = df["pct_hispanic"] > 50
mask2 = mask1 & (df["rent_burden"] > 0.3)
len(df[mask2]) / len(df[mask1])

0.5854108956602031

In [79]:
# you can sort the dataframe by values in some column
df.sort_values("pct_below_poverty", ascending=False).dropna().head()

,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,med_rooms_per_home,...,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born,state_name,monthly_income,rent_burden
GEOID10,,,,,,,,,,,,,,,,,,,,,
06037224700,6450.0,20.8,13.8,46.3,4.8,1982.0,46.2,9.0,531300.0,3.0,...,17.3,81.8,99.6,48.1,64.6,59.5,24.3,California,965.416667,1.666638
06037265303,4832.0,21.7,21.2,35.5,1.6,1747.0,42.5,0.5,578500.0,3.3,...,26.0,76.4,97.5,38.7,72.4,56.0,22.5,California,1327.000000,1.497362
06037242600,5133.0,21.1,69.5,0.1,28.6,0.0,46.5,8.4,338900.0,4.5,...,68.7,66.4,14.6,95.5,1.3,33.6,29.2,California,1352.833333,0.413946
06037221900,3627.0,21.7,26.7,19.6,9.2,1391.0,44.6,11.6,943800.0,3.1,...,36.3,66.2,92.0,67.6,33.7,42.1,44.1,California,1001.166667,1.101715
06037910403,2188.0,21.3,87.0,4.3,4.5,10.0,47.6,13.4,211100.0,4.0,...,60.9,64.6,13.6,77.2,5.3,41.9,35.9,California,1666.666667,0.505800

In [80]:
# use the describe() method to pull basic descriptive stats for some column
df["med_household_income"].describe()

count      2307.000000
mean      66213.016472
std       32487.553195
min        5682.000000
25%       41795.000000
50%       59444.000000
75%       82125.000000
max      250001.000000
Name: med_household_income, dtype: float64

#### Or if you need the value of a single stat, call it directly

Key measures of central tendency: mean and median

In [81]:
# the mean, or "average" value
df["med_household_income"].mean()

np.float64(66213.01647160815)

In [82]:
# the median, or "typical" (ie, 50th percentile) value
df["med_household_income"].median()

59444.0

In [86]:
# now it's your turn
# create a new subset dataframe containing rows with median household income above the (tract)
# average in LA county... what is the median median home value across this subset of tracts?

df["med_household_income"] > df["med_household_income"].mean()
df[mask]["med_home_value"].median()

450850.0

Key measures of dispersion or variability: range, IQR, variance, standard deviation

In [87]:
df["med_household_income"].min()

5682.0

In [88]:
# which tract has the lowest median household income?
df["med_household_income"].idxmin()

'06037222700'

In [89]:
df["med_household_income"].max()

250001.0

In [90]:
# what is the 90th-percentile value?
df["med_household_income"].quantile(0.90)

np.float64(106941.0)

In [91]:
# calculate the distribution's range
df["med_household_income"].max() - df["med_household_income"].min()

244319.0

In [92]:
# calculate its IQR
df["med_household_income"].quantile(0.75) - df["med_household_income"].quantile(0.25)

np.float64(40330.0)

In [93]:
# calculate its variance... rarely used in practice
df["med_household_income"].var()

1055441112.6259222

In [94]:
# calculate its standard deviation
# this is the sqrt of the variance... putting it into same units as the variable itself
df["med_household_income"].std()

32487.553195430435

In [99]:
# now it's your turn
# what's the average (mean) median home value across majority-White tracts?
# And across majority-Black tracts?


df_white = df[df["pct_white"] > 50 ]
df_black = df[df["pct_black"] > 50 ]
df_white["med_home_value"].mean()

np.float64(407850.9090909091)

In [100]:
df_black["med_home_value"].mean()

np.float64(407850.9090909091)

## 6. Merge and concatenate

### 6a. Merging DataFrames

In [101]:
# create a subset dataframe with only race/ethnicity variables
race_cols = ["pct_asian", "pct_black", "pct_hispanic", "pct_white"]
df_race = df[race_cols]
df_race.head()

             pct_asian  pct_black  pct_hispanic  pct_white
GEOID10
06037106010      145.0        3.6          73.6       14.8
06037106020       92.0        1.0          81.1       15.4
06037134720      991.0        5.0          46.9       23.2
06037137201     1315.0        4.9          19.2       53.6
06037137502      174.0       10.8          13.2       67.2

In [102]:
# create a subset dataframe with only economic variables
econ_cols = ["med_home_value", "med_household_income"]
df_econ = df[econ_cols].sort_values("med_household_income")
df_econ.head()

             med_home_value  med_household_income
GEOID10
06037222700             NaN                5682.0
06037206300             NaN               10262.0
06037224700        531300.0               11585.0
06037980010        839300.0               11938.0
06037221900        943800.0               12014.0

In [103]:
# merge them together, aligning rows based on their labels in the index
df_merged = pd.merge(left=df_econ, right=df_race, how="inner", left_index=True, right_index=True)
df_merged.head()

,med_home_value,med_household_income,pct_asian,pct_black,pct_hispanic,pct_white
GEOID10,,,,,,
06037222700,NaN,5682.0,1370.0,5.8,10.4,44.8
06037206300,NaN,10262.0,76.0,52.5,20.3,21.9
06037224700,531300.0,11585.0,1982.0,4.8,13.8,46.3
06037980010,839300.0,11938.0,28.0,2.3,45.9,30.8
06037221900,943800.0,12014.0,1391.0,9.2,26.7,19.6

In [104]:
# reset df_econ's index
df_econ = df_econ.reset_index()
df_econ.head()

       GEOID10  med_home_value  med_household_income
0  06037222700             NaN                5682.0
1  06037206300             NaN               10262.0
2  06037224700        531300.0               11585.0
3  06037980010        839300.0               11938.0
4  06037221900        943800.0               12014.0

In [105]:
# merge them together, aligning rows based on their labels in the index
# doesn't work! their indexes do not share any labels to match/align the rows
df_merged = pd.merge(left=df_econ, right=df_race, how="inner", left_index=True, right_index=True)
df_merged

Empty DataFrame
Columns: [GEOID10, med_home_value, med_household_income, pct_asian, pct_black, pct_hispanic, pct_white]
Index: []

In [107]:
# now it's your turn
# change the "how" argument: what happens if you try an "outer" join?
# or a "left" join? or a "right" join?

df_merged = pd.merge(left=df_econ, right=df_race, how="outer", left_on="GEOID10", right_index=True)
df_merged.head()

,GEOID10,med_home_value,med_household_income,pct_asian,pct_black,pct_hispanic,pct_white
892,06037101110,437900.0,51209.0,282.0,1.1,37.1,54.1
1794,06037101122,580400.0,85460.0,253.0,0.0,8.9,81.5
267,06037101210,360600.0,34627.0,149.0,2.8,52.7,41.2
494,06037101220,392000.0,40273.0,395.0,1.6,30.5,50.5
1705,06037101300,545200.0,81076.0,245.0,2.6,9.3,81.7

In [106]:
# instead merge where df_race index matches df_econ GEOID10 column
df_merged = pd.merge(left=df_econ, right=df_race, how="inner", left_on="GEOID10", right_index=True)
df_merged.head()

,GEOID10,med_home_value,med_household_income,pct_asian,pct_black,pct_hispanic,pct_white
0,06037222700,NaN,5682.0,1370.0,5.8,10.4,44.8
1,06037206300,NaN,10262.0,76.0,52.5,20.3,21.9
2,06037224700,531300.0,11585.0,1982.0,4.8,13.8,46.3
3,06037980010,839300.0,11938.0,28.0,2.3,45.9,30.8
4,06037221900,943800.0,12014.0,1391.0,9.2,26.7,19.6

### 6b. Concatenating DataFrames

In [108]:
# load the orange county tracts data
filepath = "https://raw.githubusercontent.com/gboeing/ppd534/main/data/census_tracts_data_oc.csv"
oc = pd.read_csv(filepath, dtype={"GEOID10": str})
oc = oc.set_index("GEOID10")
oc.shape

(583, 24)

In [109]:
oc.head()

,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,med_rooms_per_home,...,med_gross_rent,med_household_income,mean_commute_time,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born
GEOID10,,,,,,,,,,,,,,,,,,,,,
06059110110,5885.0,35.9,30.6,32.4,3.0,1676.0,49.8,63.7,471600.0,4.7,...,1573.0,73575.0,32.3,77.1,12.2,38.2,87.0,32.8,51.5,34.4
06059110115,3761.0,45.3,14.9,20.7,10.3,1941.0,49.2,84.2,609500.0,6.7,...,1771.0,98750.0,29.5,81.7,3.4,37.8,94.7,43.6,58.8,34.3
06059110116,4748.0,42.9,17.6,24.5,5.6,2168.0,49.6,68.9,634800.0,6.1,...,1406.0,94199.0,29.7,80.0,8.4,48.9,96.8,50.3,50.3,36.3
06059089001,7696.0,40.8,40.2,4.0,0.0,4273.0,50.8,58.2,358400.0,5.1,...,1489.0,53732.0,27.6,77.4,19.2,33.1,90.5,10.8,10.9,62.4
06059075702,3479.0,46.0,15.4,70.8,0.1,380.0,46.3,92.9,724500.0,6.8,...,1719.0,98864.0,21.7,83.5,2.1,21.4,92.7,48.7,81.7,12.6

In [110]:
# merging joins data together aligned by the index, but concatenating just smushes
# it together along some axis
df_all = pd.concat([df, oc], sort=False)
df_all

,total_pop,median_age,pct_hispanic,pct_white,pct_black,pct_asian,pct_male,pct_single_family_home,med_home_value,med_rooms_per_home,...,pct_commute_drive_alone,pct_below_poverty,pct_college_grad_student,pct_same_residence_year_ago,pct_bachelors_degree,pct_english_only,pct_foreign_born,state_name,monthly_income,rent_burden
GEOID10,,,,,,,,,,,,,,,,,,,,,
06037106010,3342.0,38.2,73.6,14.8,3.6,145.0,47.0,77.2,460800.0,6.3,...,76.2,21.3,23.8,87.9,20.4,42.1,28.1,California,6137.500000,0.239674
06037106020,5937.0,37.9,81.1,15.4,1.0,92.0,51.9,95.8,441100.0,6.2,...,82.5,11.4,36.9,95.1,15.5,29.0,37.5,California,6190.500000,0.310799
06037134720,4645.0,33.6,46.9,23.2,5.0,991.0,49.9,40.2,450600.0,4.2,...,73.6,13.0,32.6,87.4,25.0,32.6,42.2,California,5114.333333,0.277260
06037137201,6226.0,33.4,19.2,53.6,4.9,1315.0,50.8,34.9,605300.0,4.4,...,71.3,7.1,29.9,86.0,51.0,54.5,39.2,California,6244.666667,0.282321
06037137502,4627.0,41.9,13.2,67.2,10.8,174.0,47.1,77.0,668400.0,5.4,...,84.9,5.7,22.9,80.8,54.9,77.9,20.1,California,8080.333333,0.287736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
06059075202,5510.0,33.3,91.2,3.8,0.2,254.0,47.5,73.5,417500.0,4.8,...,63.7,23.4,29.5,94.3,9.0,14.3,48.9,NaN,NaN,NaN
06059075301,5994.0,29.2,66.6,21.1,1.5,568.0,50.1,55.3,616900.0,4.9,...,76.9,16.6,29.0,87.3,20.9,32.1,33.8,NaN,NaN,NaN
06059032032,3020.0,44.8,19.7,62.9,0.0,355.0,50.2,95.9,697200.0,6.4,...,82.9,6.7,26.6,84.9,40.4,80.1,18.2,NaN,NaN,NaN
06059032035,2356.0,56.5,9.0,75.5,1.1,231.0,47.3,49.5,741600.0,6.2,...,78.6,4.0,37.3,85.6,52.1,80.3,20.7,NaN,NaN,NaN
06059032038,6482.0,45.5,10.8,68.2,0.0,1080.0,49.0,88.9,792300.0,7.3,...,77.5,3.7,30.9,92.5,58.7,81.0,20.8,NaN,NaN,NaN

## 7. Grouping and summarizing

In [111]:
# extract county fips from index then replace with friendly name
df_all["county"] = df_all.index.str.slice(2, 5)
df_all["county"] = df_all["county"].replace({"037": "LA", "059": "OC"})
df_all["county"]

GEOID10
06037106010    LA
06037106020    LA
06037134720    LA
06037137201    LA
06037137502    LA
               ..
06059075202    OC
06059075301    OC
06059032032    OC
06059032035    OC
06059032038    OC
Name: county, Length: 2929, dtype: object

In [117]:
# group the rows by county
counties = df_all.groupby("county")

In [113]:
# what is the median pct_white across the tracts in each county?
counties["pct_white"].median()

county
LA    17.10
OC    46.75
Name: pct_white, dtype: float64

In [116]:
# look at several columns' medians by county
counties[["pct_bachelors_degree", "pct_foreign_born", "pct_commute_drive_alone"]].median()

        pct_bachelors_degree  pct_foreign_born  pct_commute_drive_alone
county
LA                      25.4              34.7                     75.1
OC                      39.8              26.6                     79.3

In [121]:
# now it's your turn
# group the tracts by county and find the highest/lowest tract percentages that speak English-only

counties = df_all.groupby("county")
counties["pct_english_only"].max()

county
LA    100.0
OC     94.5
Name: pct_english_only, dtype: float64

In [122]:
counties["pct_english_only"].min()

county
LA    3.3
OC    0.0
Name: pct_english_only, dtype: float64